# Generated by Django 4.2.1 on 2023-05-24 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('date', models.DateField(default=datetime.date(2023, 5, 24))),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Midnight Snack', 'Midnight Snack')], default='Breakfast', max_length=20)),
                ('food_name', models.CharField(max_length=60)),
                ('calorie', models.IntegerField(help_text='The unit is kcal')),
                ('location', models.CharField(help_text='Enter the place you buy the food.', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('lastest_revised_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
