# Generated by Django 4.2.1 on 2023-05-26 18:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_meal_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('location', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_revised_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shop_name'],
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='location',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 26)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Midnight Snack', 'Midnight Snack')], default='Breakfast', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('ingredients', models.TextField()),
                ('calorie', models.IntegerField(help_text='The unit is kcal', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.')])),
                ('price', models.IntegerField(help_text='The unit is $NT', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_revised_date', models.DateTimeField(auto_now=True)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='diet.restaurant')),
            ],
            options={
                'ordering': ['food_name'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(to='diet.menu'),
        ),
    ]
