# Generated by Django 4.2.1 on 2023-05-31 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_restaurant_remove_meal_calorie_remove_meal_food_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='resturant',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 19, 22, 52, 139121)),
        ),
    ]
